# Site settings
title: ONZO.art
email: web.art@adriandiaz.ca
description: "The home of Ridia Onzo's artist portfolio."
url: "http://127.0.0.1:4000"  # http://127.0.0.1:4000
                           # http://www.onzo.ca
twitter_username: adgr72
github_username:  adriandgr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock", "CNAME"]


collections:
  contributors:
    output: true
    permalink: /contributors/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Site owner
owner:
  name: Ridia Onzo
  display_name: Onzo
  web: http://www.onzo.ca
  email: obj.art@onzo.ca
  twitter: adgr72
  github: adriandgr
  gravatar: 1092e44f33d0454dfb580e19f3687ce8
  bio: "A Vancouver-based artist"
  avatar: bio/shifting.jpg # 160x160 px image for author byline
  google:
    plus: +AdrianDiazArt
    ad-client: ca-pub-(+16digit)
    ad-slot: (10digitNumber)
  disqus-shortname: adriandiaz

authors:
  onzo:
    display_name: Ridia Onzo
    gravatar: 1092e44f33d0454dfb580e19f3687ce8
    email: obj.art@onzo.ca
    web: http://www.onzo.ca/
    twitter: adgr72
    github: adriandgr
  adrian:
    display_name: Adrian Diaz
    gravatar: 1092e44f33d0454dfb580e19f3687ce8
    email: web.art@adriandiaz.ca
    web: http://www.adriandiaz.ca/
    twitter: adgr72
    github: adriandgr
